apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-model-deployment
  annotations:
    kubernetes.io/ingress.class: "nginx"  
  # labels:
  #   app: tiangolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ids-model
  template:
    metadata:
      labels:
        app: ids-model
    spec:
      containers:
      - name: ids-model
        image: asture123/detector
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ids-model-service
spec:
  selector:
    app: ids-model
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 3001
#      nodePort: 30000
#  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ids-model-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: idsmodel.com
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ids-model-service
            port:
              number: 1935
