apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-model-deployment
  # labels:
  #   app: tiangolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ids-model
  template:
    metadata:
      labels:
        app: ids-model
    spec:
      containers:
      - name: ids-model
        image: asture123/detector
        ports:
        - containerPort: 1935
---
apiVersion: v1
kind: Service
metadata:
  name: ids-model-service
spec:
  selector:
    app: ids-model
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 4000
      nodePort: 30000
  type: NodePort
