apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby-server
  template:
    metadata:
      labels:
        app: emby-server
    spec:
      containers:
      - name: emby-server
        image: emby/embyserver:latest
        ports:
        - containerPort: 8096
        - containerPort: 8920
        volumeMounts:
        - mountPath: /config
          name: emby-config
        - mountPath: /mnt/share1
          name: emby-data
        # - mountPath: /mnt/share2
        #   name: emby-s3
      volumes:
      - name: emby-config
        persistentVolumeClaim:
          claimName: emby-config-pvc
      - name: emby-data
        persistentVolumeClain:
          claimName: emby-data-pvc
      nodeSelector:
        nodename: worker3
---
apiVersion: v1
kind: Service
metadata:
  name: emby-server
  labels:
    run: emby-server
spec:
  type: LoadBalancer
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
    name: http
  - port: 8920
    protocol: TCP
    targetPort: 8920
    name: https
  selector:
    run: emby-server
