apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby-server
  template:
    metadata:
      labels:
        app: emby-server
    spec:
      containers:
      - name: emby-server
        image: emby/embyserver
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "100"
        - name: GIDLIST
          value: "100"        
        ports:
        - containerPort: 8096
        - containerPort: 8920
        volumeMounts:
        - mountPath: /config
          name: emby-config
        - mountPath: /mnt/share1
          name: emby-shows
        - mountPath: /mnt/share2
          name: emby-movies
      volumes:
      - name: emby-config
        persistentVolumeClaim:
          claimName: emby-config-pvc
      - name: emby-shows
        persistentVolumeClaim:
          claimName: emby-shows-pvc
      - name: emby-movies
        persistentVolumeClaim:
          claimName: emby-movies-pvc          
      nodeSelector:
        nodename: worker3
---
apiVersion: v1
kind: Service
metadata:
  name: emby-server
  labels:
    run: emby-server
spec:
  type: LoadBalancer
  selector:
    app: emby-server
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
    # nodePort: 32096
    name: http
  - port: 8920
    protocol: TCP
    targetPort: 8920
    # nodePort: 32120
    name: https

