apiVersion: v1
kind: PersistentVolume
metadata:
  name: packet-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/pv/pv1"  # Replace with a path on your node
